//this variable stores a random string generated by the function
//getRandomString. The function takes one argument which is the 
//length of the random string that the function returns.
let rndString = getRandomString(3);
console.log(rndString);

function getRandomString(numberOfLetters){
    //The letters we can choose from 
    const alphabet = 'abcdefghijklmnopqrstuvxyz';
    let randomString = '';

    //This for loop will run as many times as the chosen number of letters
    for(let i=0; i<numberOfLetters; i++){
        //get a random nummber between 0 and the length of the string alphabet
        //Match.floor rounds the number downward to the closest integer
        let randomNumber = Math.floor(Math.random()*alphabet.length);

        //Add a random letter from the string alphabet to the string randomString
        //charAt() gets a character from a string at a specifiv index number 
        randomString += alphabet.charAt(randomNumber);
    }

    //Makes the function return the random string so that we 
    //can use it whenever we call the function
    return randomString;
}